name: DeepFins
channels:
	defaults
dependencies: 
	absl-py==0.13.0
	aiofiles==23.2.1
	alabaster==0.7.12
	alembic==1.9.1
	altair==5.4.1
	aniso8601==9.0.1
	annotated-types==0.7.0
	anyio==3.6.1
	appdirs==1.4.4
	apt-clone==0.2.1
	apturl==0.5.2
	argon2-cffi==21.3.0
	argon2-cffi-bindings==21.2.0
	arrow==1.2.3
	astroid==2.13.3
	asttokens==2.0.8
	astunparse==1.6.3
	atomicwrites==1.4.1
	attrs==22.1.0
	audioread==2.1.9
	autopep8==1.6.0
	avalanche-lib==0.5.0
	Babel==2.10.3
	backcall==0.2.0
	bcrypt==3.1.7
	beautifulsoup4==4.11.1
	binaryornot==0.4.4
	black==22.12.0
	bleach==5.0.1
	blinker==1.4
	boto3==1.34.79
	botocore==1.34.79
	Brlapi==0.7.0
	bs4==0.0.1
	cachetools==4.2.4
	caffeine==2.9.4
	certifi==2021.10.8
	cffi==1.15.1
	chardet==3.0.4
	charset-normalizer==2.1.1pip freeze > environment.yml
	clarabel==0.7.1
	click==8.1.3
	cloudpickle==2.2.0
	cmake==3.26.3
	cmeel==0.53.3
	colorama==0.4.5
	comm==0.1.2
	command-not-found==0.3
	contourpy==1.1.1
	cookiecutter==2.1.1
	cosine-annealing-warmup @ git+https://github.com/katsura-jp/pytorch-cosine-annealing-with-warmup@12d03c07553aedd3d9e9155e2b3e31ce8c64081a
	cryptography==2.8
	ctrl-benchmark==0.0.4
	cupshelpers==1.0
	cvxopt==1.3.2
	cycler==0.11.0
	Cython==0.29.32
	daqp==0.5.1.post1
	databricks-cli==0.17.4
	dbus-python==1.2.16
	dcor==0.6
	debugpy==1.8.1
	decorator==5.1.1
	defer==1.0.6
	defusedxml==0.7.1
	diff-match-patch==20200713
	dill==0.3.6
	distlib==0.3.0
	distro==1.4.0
	distro-info==0.23+ubuntu1.1
	dnspython==1.16.0
	docker==6.0.1
	docker-pycreds==0.4.0
	docstring-to-markdown==0.11
	docutils==0.19
	duplicity==0.8.12.0
	easyocr==1.5.0
	ecos==2.0.13
	efficientnet-pytorch==0.7.1
	einops==0.7.0
	emd==0.6.2
	encodec==0.1.1
	entrypoints==0.3
	ewmh==0.1.6
	executing==1.1.0
	fastapi==0.115.0
	fasteners==0.14.1
	fastjsonschema==2.16.2
	ffmpy==0.4.0
	filelock==3.8.0
	flake8==6.0.0
	Flask==2.2.2
	flatbuffers==1.12
	fonttools==4.37.3
	fsspec==2024.3.1
	funcy==2.0
	furo==2022.9.29
	future==0.18.2
	gast==0.4.0
	gdown==4.5.1
	gensim==4.2.0
	gitdb==4.0.9
	GitPython==3.1.27
	google-auth==1.35.0
	google-auth-oauthlib==0.4.6
	google-pasta==0.2.0
	GPUtil==1.4.0
	gradio==4.29.0
	gradio_client==0.16.1
	gradio_imageslider==0.0.18
	graphene==3.3
	graphql-core==3.2.3
	graphql-relay==3.2.0
	greenlet==2.0.1
	grpcio==1.47.0
	gunicorn==21.2.0
	gym==0.26.2
	gym-notices==0.0.8
	h11==0.14.0
	h5py==2.10.0
	higher==0.2.1
	highspy==1.7.1.dev1
	httpcore==1.0.6
	httplib2==0.14.0
	httpx==0.27.2
	huggingface-hub==0.22.2
	idna==3.4
	imageio==2.21.1
	imagesize==1.4.1
	importlib-metadata==4.12.0
	importlib-resources==5.9.0
	inflection==0.5.1
	intervaltree==3.1.0
	ipykernel==6.29.4
	ipython==8.5.0
	ipython-genutils==0.2.0
	ipywidgets==8.0.2
	iso8601==1.0.2
	isodate==0.6.1
	isort==5.11.4
	itsdangerous==2.1.2
	jarowinkler==1.2.0
	jedi==0.18.1
	jellyfish==0.9.0
	Jinja2==3.1.2
	jinja2-time==0.2.0
	jmespath==1.0.1
	joblib==1.2.0
	json5==0.9.10
	jsonschema==4.16.0
	jupyter-server==1.19.0
	jupyter_client==7.4.9
	jupyter_core==5.7.2
	jupyterlab==3.5.0
	jupyterlab-pygments==0.2.2
	jupyterlab-widgets==3.0.3
	jupyterlab_server==2.15.2
	keras==2.8.0
	Keras-Applications==1.0.2
	keras-nightly==2.5.0.dev2021032900
	Keras-Preprocessing==1.1.2
	keyring==18.0.1
	kiwisolver==1.4.4
	language-selector==0.1
	launchpadlib==1.10.13
	lazr.restfulclient==0.14.2
	lazr.uri==1.0.3
	lazy-object-proxy==1.9.0
	Levenshtein==0.20.2
	libclang==14.0.6
	librosa==0.8.1
	lightning-utilities==0.11.1
	lit==16.0.2
	lockfile==0.12.2
	louis==3.12.0
	lvis==0.5.3
	lxml==4.9.1
	m3u8==1.0.0
	macaroonbakery==1.3.1
	Mako==1.2.4
	Markdown==3.3.4
	markdown-it-py==2.2.0
	MarkupSafe==2.1.1
	matplotlib==3.5.2
	matplotlib-inline==0.1.6
	mccabe==0.7.0
	mdurl==0.1.2
	mistune==2.0.4
	mlflow==2.11.3
	monotonic==1.5
	more-itertools==4.2.0
	mpmath==1.3.0
	mtcnn==0.1.1
	mypy-extensions==0.4.3
	nano==0.10.0
	narwhals==1.9.2
	natsort==8.1.0
	nbclassic==0.4.3
	nbclient==0.6.8
	nbconvert==7.0.0
	nbformat==5.6.1
	nest-asyncio==1.5.5
	netifaces==0.10.4
	networkx==2.8.6
	notebook==6.4.12
	notebook-shim==0.1.0
	numpy==1.23.3
	numpydoc==1.5.0
	nvidia-cublas-cu11==11.10.3.66
	nvidia-cublas-cu12==12.1.3.1
	nvidia-cuda-cupti-cu11==11.7.101
	nvidia-cuda-cupti-cu12==12.1.105
	nvidia-cuda-nvrtc-cu11==11.7.99
	nvidia-cuda-nvrtc-cu12==12.1.105
	nvidia-cuda-runtime-cu11==11.7.99
	nvidia-cuda-runtime-cu12==12.1.105
	nvidia-cudnn-cu11==8.5.0.96
	nvidia-cudnn-cu12==9.1.0.70
	nvidia-cufft-cu11==10.9.0.58
	nvidia-cufft-cu12==11.0.2.54
	nvidia-curand-cu11==10.2.10.91
	nvidia-curand-cu12==10.3.2.106
	nvidia-cusolver-cu11==11.4.0.1
	nvidia-cusolver-cu12==11.4.5.107
	nvidia-cusparse-cu11==11.7.4.91
	nvidia-cusparse-cu12==12.1.0.106
	nvidia-nccl-cu11==2.14.3
	nvidia-nccl-cu12==2.20.5
	nvidia-nvjitlink-cu12==12.4.127
	nvidia-nvtx-cu11==11.7.91
	nvidia-nvtx-cu12==12.1.105
	oauthlib==3.2.1
	olefile==0.46
	opencv-python==4.7.0.72
	opencv-python-headless==4.5.4.60
	opt-einsum==3.3.0
	orjson==3.10.7
	osqp==0.6.5
	packaging==24.0
	PAM==0.4.2
	pandas==1.3.5
	pandocfilters==1.5.0
	paramiko==2.6.0
	parso==0.8.3
	pathspec==0.11.0
	pathtools==0.1.2
	pdfminer.six==20211012
	pdfplumber==0.6.0
	peakdetect==1.2
	pexpect==4.6.0
	pickleshare==0.7.5
	Pillow==9.5.0
	piqp==0.2.4
	pkgconfig==1.5.5
	pkgutil_resolve_name==1.3.10
	platformdirs==2.6.2
	plotly==5.10.0
	pluggy==1.0.0
	pooch==1.5.2
	prometheus-client==0.14.1
	promise==2.3
	prompt-toolkit==3.0.31
	protobuf==3.20.2
	proxsuite==0.6.3
	psutil==5.9.4
	ptyprocess==0.7.0
	pure-eval==0.2.2
	pyarrow==15.0.2
	pyasn1==0.4.8
	pyasn1-modules==0.2.8
	pybgs==3.0.0.post2
	pycairo==1.16.2
	pycocotools==2.0
	pycodestyle==2.10.0
	pycountry==22.1.10
	pycparser==2.21
	pycrypto==2.6.1
	pycryptodome==3.12.0
	pycups==1.9.73
	pydantic==2.9.2
	pydantic_core==2.23.4
	pydata-sphinx-theme==0.12.0
	pydocstyle==6.2.3
	pydot==1.4.2
	pydub==0.25.1
	pyemd==1.0.0
	pyflakes==3.0.1
	Pygments==2.13.0
	PyGObject==3.36.0
	PyICU==2.4.2
	PyJWT==2.6.0
	pylint==2.15.10
	pylint-venv==2.3.0
	pyls-spyder==0.4.0
	pymacaroons==0.13.0
	pymongo==4.0.1
	PyNaCl==1.3.0
	pyparsing==3.0.9
	PyQt5==5.15.7
	PyQt5-Qt5==5.15.2
	PyQt5-sip==12.11.0
	PyQtWebEngine==5.15.6
	PyQtWebEngine-Qt5==5.15.2
	pyRFC3339==1.1
	pyrsistent==0.18.1
	PySocks==1.7.1
	pytesseract==0.3.9
	python-apt==2.0.1+ubuntu0.20.4.1
	python-bidi==0.4.2
	python-dateutil==2.8.2
	python-debian==0.1.36+ubuntu1.1
	python-lsp-black==1.2.1
	python-lsp-jsonrpc==1.0.0
	python-lsp-server==1.7.1
	python-multipart==0.0.12
	python-slugify==7.0.0
	python-version==0.0.2
	python-xlib==0.23
	pytoolconfig==1.2.4
	pytorchcv==0.0.67
	pyts==0.13.0
	pytz==2022.2.1
	PyWavelets==1.3.0
	pyxdg==0.26
	PyYAML==6.0
	pyzmq==24.0.1
	QDarkStyle==3.0.3
	qdldl==0.1.7.post0
	qpalm==1.2.2
	qpsolvers==4.3.2
	qstylizer==0.2.2
	QtAwesome==1.2.2
	qtconsole==5.4.0
	QtPy==2.3.0
	quadprog==0.1.12
	querystring-parser==1.2.4
	rapidfuzz==2.4.3
	regex==2022.10.31
	reportlab==3.5.34
	requests==2.32.3
	requests-oauthlib==1.3.1
	requests-unixsocket==0.2.0
	resampy==0.2.2
	rich==13.4.1
	rope==1.7.0
	rsa==4.9
	Rtree==1.0.1
	ruff==0.6.9
	s3transfer==0.10.1
	safetensors==0.4.5
	scikit-build==0.14.1
	scikit-image==0.19.3
	scikit-learn==1.3.1
	scipy==1.10.1
	screen-resolution-extra==0.0.0
	scs==3.2.4.post1
	seaborn==0.12.2
	SecretStorage==2.3.1
	semantic-version==2.10.0
	Send2Trash==1.8.0
	sentry-sdk==1.9.9
	setproctitle==1.3.2
	shap==0.44.1
	shellingham==1.5.4
	shortuuid==1.0.9
	simplejson==3.16.0
	six==1.14.0
	sklearn==0.0
	slicer==0.0.7
	smart-open==6.0.0
	smmap==5.0.0
	sniffio==1.3.0
	snowballstemmer==2.2.0
	sortedcontainers==2.4.0
	SoundFile==0.10.3.post1
	soupsieve==2.3.2.post1
	sparse==0.14.0
	Sphinx==5.3.0
	sphinx-basic-ng==1.0.0b1
	sphinx-copybutton==0.5.1
	sphinx_design==0.3.0
	sphinxcontrib-applehelp==1.0.2
	sphinxcontrib-devhelp==1.0.2
	sphinxcontrib-htmlhelp==2.0.0
	sphinxcontrib-jsmath==1.0.1
	sphinxcontrib-qthelp==1.0.3
	sphinxcontrib-serializinghtml==1.1.5
	spyder==5.4.2
	spyder-kernels==2.4.2
	SQLAlchemy==1.4.46
	sqlparse==0.4.3
	stack-data==0.5.1
	starlette==0.38.6
	streamlink==3.0.3
	suno-bark @ file:///home/ahsanjalal/bark
	sympy==1.11.1
	systemd-python==234
	tabulate==0.9.0
	tenacity==8.1.0
	tensorboard==2.8.0
	tensorboard-data-server==0.6.1
	tensorboard-plugin-wit==1.8.1
	tensorflow==2.8.1
	tensorflow-estimator==2.8.0
	tensorflow-io-gcs-filesystem==0.26.0
	tensorrt==8.6.1
	tensorrt-dispatch==8.6.1
	tensorrt-lean==8.6.1
	termcolor==1.1.0
	terminado==0.18.1
	tesseract==0.1.3
	text-unidecode==1.3
	textdistance==4.5.0
	thop==0.1.1.post2209072238
	threadpoolctl==3.0.0
	three-merge==0.1.1
	tifffile==2022.8.12
	timm==1.0.11
	tinycss2==1.2.1
	tokenizers==0.13.3
	toml==0.10.2
	tomli==2.0.1
	tomlkit==0.12.0
	torch==2.4.0
	torchmetrics==1.3.2
	torchsummary==1.5.1
	torchvision==0.19.0
	tornado==6.2
	tqdm==4.64.0
	traitlets==5.4.0
	transformers==4.29.0
	triton==3.0.0
	ttach==0.0.3
	typer==0.12.5
	typing_extensions==4.11.0
	ubuntu-advantage-tools==8001
	ubuntu-drivers-common==0.0.0
	ufw==0.36
	ujson==5.7.0
	ultralytics==8.0.91
	unattended-upgrades==0.1
	urllib3==2.2.3
	usb-creator==0.3.7
	uvicorn==0.31.0
	virtualenv==20.0.17
	wadllib==1.3.3
	waitress==2.1.2
	Wand==0.6.7
	wandb==0.13.3
	watchdog==2.2.1
	wcwidth==0.2.6
	webencodings==0.5.1
	websocket-client==1.4.1
	websockets==11.0.3
	Werkzeug==2.2.2
	whatthepatch==1.0.3
	widgetsnbextension==4.0.3
	wincertstore==0.2
	wrapt==1.12.1
	wurlitzer==3.0.3
	xkit==0.0.0
	yapf==0.32.0
	youtube-dl==2021.12.17
	zipp==3.8.1
